// The in-app Help Guide content. Every screen follows the same 4-part template:
// purpose (1 sentence), screenshot placeholder, numbered steps (**bold** = a UI
// element to click or type into), and a pro-tip. Rendered by help-panel.tsx.

export type HelpSection = {
  id: string          // anchor id — used to deep-link a screen to its guide entry
  title: string
  purpose: string
  screenshot: string  // description of the screenshot that belongs here
  steps: string[]     // **bold** marks buttons/fields
  proTip: string
  href?: string       // web route this screen lives at — auto-opens the matching entry
  link?: { label: string; href: string } // extra "read more" link (e.g. Stripe guide)
}

export type HelpGroup = { label: string; sections: HelpSection[] }
export type HelpPart = { id: string; label: string; groups: HelpGroup[] }

// Section ids that have a real screenshot at /public/help/{id}.png. Sections not
// listed here fall back to the dashed "[Screenshot: …]" placeholder (e.g. the
// phone screens and Bills, which weren't captured yet).
export const HELP_SCREENSHOTS = new Set([
  'web-dashboard', 'web-projects', 'web-messages', 'web-enquiries', 'web-customers',
  'web-quotes', 'web-jobs', 'web-job-map', 'web-schedule', 'web-time-logs', 'web-logbook',
  'web-invoices', 'web-forms', 'web-todo', 'web-purchase-orders', 'web-suppliers',
  'web-price-list', 'web-reports', 'web-website', 'web-bookings', 'web-settings',
])

export const HELP_GUIDE: HelpPart[] = [
  {
    id: 'web',
    label: 'Part 1 — The Web App',
    groups: [
      {
        label: 'Main Menu',
        sections: [
          {
            id: 'web-dashboard',
            title: 'Dashboard',
            purpose: 'Your whole business at a glance.',
            screenshot: 'Screenshot: The dashboard with the stat cards across the top and the activity feed below.',
            href: '/dashboard',
            steps: [
              'Look at the top cards. They show jobs, quotes and money.',
              'Click any card to jump to that list.',
              'Scroll down for recent activity.',
              'Use the sidebar on the left to go anywhere.',
            ],
            proTip: 'Start every morning here. Ten seconds tells you what needs attention today.',
          },
          {
            id: 'web-projects',
            title: 'Projects',
            purpose: 'Big jobs broken into smaller pieces.',
            screenshot: 'Screenshot: The projects list with one project expanded to show its jobs.',
            href: '/projects',
            steps: [
              'Click **Projects** in the sidebar.',
              'Click **New Project**.',
              'Give it a name.',
              'Add jobs to the project.',
              'Watch progress roll up automatically.',
            ],
            proTip: 'Use a project for anything with more than one visit — like a full renovation. One job per stage keeps invoicing simple.',
          },
        ],
      },
      {
        label: 'Customers & Jobs',
        sections: [
          {
            id: 'web-messages',
            title: 'Messages',
            purpose: 'Chat with clients and your team in one inbox.',
            screenshot: 'Screenshot: The messages screen with a conversation open and the reply box at the bottom.',
            href: '/messages',
            steps: [
              'Click **Messages** in the sidebar.',
              'Click a conversation to open it.',
              'Type your reply at the bottom.',
              'Press **Send**.',
            ],
            proTip: 'A red badge on Messages means something is unread. Clear it daily — fast replies win work.',
          },
          {
            id: 'web-enquiries',
            title: 'Enquiries',
            purpose: 'New leads — people asking you for work.',
            screenshot: 'Screenshot: The enquiries list with a new enquiry highlighted and the Convert button visible.',
            href: '/enquiries',
            steps: [
              'Click **Enquiries** in the sidebar.',
              'Click an enquiry to read it.',
              'Like the job? Convert it to a **Quote**.',
              'Not a fit? Mark it closed.',
            ],
            proTip: 'Reply to enquiries within an hour if you can. The first tradie to answer usually gets the job.',
          },
          {
            id: 'web-customers',
            title: 'Customers',
            purpose: 'Your client address book.',
            screenshot: 'Screenshot: The customers list with the New Customer button top right.',
            href: '/customers',
            steps: [
              'Click **Customers** in the sidebar.',
              'Click **New Customer**.',
              'Type their name and contact details.',
              'Click **Save**.',
              'Click any customer to see their full history.',
            ],
            proTip: 'Always add the site address, not just a phone number. It powers the Job Map and driving directions later.',
          },
          {
            id: 'web-quotes',
            title: 'Quotes',
            purpose: 'Price up work before you start.',
            screenshot: 'Screenshot: A quote being edited, with line items and the Send button highlighted.',
            href: '/quotes',
            steps: [
              'Click **Quotes** in the sidebar.',
              'Click **New Quote**.',
              'Pick the customer.',
              'Add line items — materials and labour.',
              'Click **Send** to email it.',
              'When they say yes, convert it to a **Job**.',
            ],
            proTip: 'Pull prices from your Price List instead of typing them. Same price every time, no math mistakes.',
          },
          {
            id: 'web-jobs',
            title: 'Jobs',
            purpose: 'The work you are doing right now.',
            screenshot: 'Screenshot: The jobs list showing status colours, with one job open showing its tabs.',
            href: '/jobs',
            steps: [
              'Click **Jobs** in the sidebar.',
              'Click a job to open it.',
              'Add notes, photos, materials and time.',
              'Use the arrows to flick between jobs.',
              'Done? Change the status to **Completed**.',
              'Then click **Create Invoice**.',
            ],
            proTip: 'Add photos as you go, not at the end. Before-and-after shots stop payment disputes cold.',
          },
          {
            id: 'web-job-map',
            title: 'Job Map',
            purpose: 'See where all your jobs are on a map.',
            screenshot: 'Screenshot: The map with job pins scattered across the city, one pin popup open.',
            href: '/jobs/map',
            steps: [
              'Click **Job Map** in the sidebar.',
              'Each pin is a job.',
              'Click a pin for details.',
              'Click through to open the job.',
            ],
            proTip: 'Planning tomorrow? Group jobs that are near each other. Less driving, more paid hours.',
          },
          {
            id: 'web-schedule',
            title: 'Schedule',
            purpose: 'The master calendar for the whole team.',
            screenshot: 'Screenshot: The week view of the schedule with colour-coded visits per team member.',
            href: '/schedule',
            steps: [
              'Click **Schedule** in the sidebar.',
              'Click an empty slot to book a visit.',
              'Pick the job and the person.',
              'Click an existing visit to change its time.',
              'Click **Save**.',
            ],
            proTip: 'Booked visits show up on your team’s phones automatically. No more morning phone-around.',
          },
          {
            id: 'web-time-logs',
            title: 'Time Logs',
            purpose: 'Track hours worked on every job.',
            screenshot: 'Screenshot: The time logs list grouped by day, with the Log Time button visible.',
            href: '/time-logs',
            steps: [
              'Click **Time Logs** in the sidebar.',
              'See everyone’s hours by day.',
              'Click an entry to fix a mistake.',
              'Click **Log Time** to add hours manually.',
            ],
            proTip: 'Logged hours flow straight onto invoices. Untracked time is money you gave away for free.',
          },
          {
            id: 'web-logbook',
            title: 'Vehicle Logbook',
            purpose: 'Track van and truck mileage automatically.',
            screenshot: 'Screenshot: The logbook showing trips with distances, and the work/personal toggle.',
            href: '/logbook',
            steps: [
              'Click **Vehicle Logbook** in the sidebar.',
              'Trips are recorded from the phone app.',
              'Mark each trip **Work** or **Personal**.',
              'Assign work trips to a job.',
            ],
            proTip: 'Tag trips weekly while you still remember them. Your accountant will love you at tax time.',
          },
          {
            id: 'web-invoices',
            title: 'Invoices',
            purpose: 'Bill your clients and get paid.',
            screenshot: 'Screenshot: An invoice open, with Complete and send email highlighted and the green Emailed badge.',
            href: '/invoices',
            steps: [
              'Click **Invoices** in the sidebar.',
              'Click **New Invoice** — or create one from a job.',
              'Check the line items.',
              'Click **Complete and send email**.',
              'A green **Emailed** badge confirms it went out.',
              'Paid in person? Use **Tap to Pay** on your phone.',
            ],
            proTip: 'Invoice the same day you finish. Every day you wait, the odds of a slow payment go up.',
          },
          {
            id: 'web-forms',
            title: 'Forms',
            purpose: 'Digital paperwork filled out on site.',
            screenshot: 'Screenshot: The forms list with a form template open showing its fields.',
            href: '/forms',
            steps: [
              'Click **Forms** in the sidebar.',
              'Click **New Form** to build a template.',
              'Add your fields — text, checkboxes, signatures.',
              'Your team fills them in on site.',
              'Finished forms attach to the job.',
            ],
            proTip: 'Turn your safety checklist into a form once. Every job after that is two taps instead of paper.',
          },
          {
            id: 'web-todo',
            title: 'To-Do',
            purpose: 'Your daily checklist of tasks.',
            screenshot: 'Screenshot: The to-do list with a few items ticked off and the Add task box at the top.',
            href: '/todos',
            steps: [
              'Click **To-Do** in the sidebar.',
              'Type a task and press **Enter**.',
              'Tick the box when it’s done.',
            ],
            proTip: 'Write down "order the parts" the second you think of it. Your memory is for the trade, not the admin.',
          },
        ],
      },
      {
        label: 'Suppliers & Orders',
        sections: [
          {
            id: 'web-purchase-orders',
            title: 'Purchase Orders',
            purpose: 'Order materials from your suppliers.',
            screenshot: 'Screenshot: A purchase order being created with supplier and line items filled in.',
            href: '/purchase-orders',
            steps: [
              'Click **Purchase Orders** in the sidebar.',
              'Click **New Purchase Order**.',
              'Pick the supplier.',
              'Add the materials you need.',
              'Link it to a job.',
              'Click **Send**.',
            ],
            proTip: 'Always link the PO to a job. That’s how material costs land on the right invoice instead of vanishing.',
          },
          {
            id: 'web-bills',
            title: 'Bills',
            purpose: 'Track money you owe suppliers.',
            screenshot: 'Screenshot: The bills list showing due dates, with an overdue bill in red.',
            href: '/bills',
            steps: [
              'Click **Bills** in the sidebar.',
              'Click **New Bill** when an invoice arrives.',
              'Enter the amount and due date.',
              'Mark it **Paid** when you pay it.',
            ],
            proTip: 'Red means overdue. Pay suppliers on time — good credit gets you better prices and faster deliveries.',
          },
          {
            id: 'web-suppliers',
            title: 'Suppliers',
            purpose: 'The stores and vendors you buy from.',
            screenshot: 'Screenshot: The suppliers list with contact details and the New Supplier button.',
            href: '/suppliers',
            steps: [
              'Click **Suppliers** in the sidebar.',
              'Click **New Supplier**.',
              'Add their name and contact details.',
              'Click **Save**.',
            ],
            proTip: 'Add your rep’s direct mobile, not the store’s main line. Skips the hold music when you need something now.',
          },
          {
            id: 'web-price-list',
            title: 'Price List',
            purpose: 'Your catalogue of material and labour prices.',
            screenshot: 'Screenshot: The price list with items, costs and sell prices in columns.',
            href: '/price-list',
            steps: [
              'Click **Price List** in the sidebar.',
              'Click **New Item**.',
              'Enter what it costs you.',
              'Enter what you charge.',
              'Use these items in quotes and invoices.',
            ],
            proTip: 'Set your sell price with margin built in. If you type prices from memory, you will undercharge.',
          },
        ],
      },
      {
        label: 'Admin',
        sections: [
          {
            id: 'web-reports',
            title: 'Reports',
            purpose: 'Charts showing how the business is doing.',
            screenshot: 'Screenshot: The reports screen with revenue and job charts over the last few months.',
            href: '/reports',
            steps: [
              'Click **Reports** in the sidebar.',
              'Pick a date range.',
              'Check revenue, jobs and quote win-rate.',
            ],
            proTip: 'Watch your quote win-rate. Winning nearly everything? Your prices are probably too low.',
          },
          {
            id: 'web-website',
            title: 'Website',
            purpose: 'Your public website that customers see.',
            screenshot: 'Screenshot: The website builder with the live preview and the Publish button.',
            href: '/website',
            steps: [
              'Click **Website** in the sidebar.',
              'Edit your business info and services.',
              'Pick photos from your finished jobs.',
              'Click **Publish**.',
            ],
            proTip: 'Real job photos beat stock photos every time. Customers want to see your actual work.',
          },
          {
            id: 'web-bookings',
            title: 'Bookings',
            purpose: 'Let customers book you online.',
            screenshot: 'Screenshot: The bookings screen with available slots and a pending booking request.',
            href: '/bookings',
            steps: [
              'Click **Bookings** in the sidebar.',
              'Set the times you’re available.',
              'Customers pick a slot on your website.',
              'Accept or decline each request.',
              'You can ask for a deposit up front.',
            ],
            proTip: 'Turn on deposits. A customer with money down almost never no-shows.',
          },
          {
            id: 'web-settings',
            title: 'Settings',
            purpose: 'Set up your business, team and payments.',
            screenshot: 'Screenshot: The settings screen with the tab bar: Business, Workflow, Team, My profile, Integrations, Subscription, Test Mode, Help.',
            href: '/settings',
            steps: [
              'Click **Settings** in the sidebar.',
              'Use **Business** for your company details and logo.',
              'Use **Team** to invite your workers.',
              'Use **Subscription** for your plan — and card payments.',
              'Want Tap to Pay? Click **Set up payouts** there.',
              'Stuck? The **Help** tab has step-by-step guides.',
            ],
            proTip: 'Set up payouts before your first job ends. Then you can take card payment on the spot instead of chasing a bank transfer.',
            link: { label: 'Full guide: Getting paid with Tap to Pay →', href: '/settings/help/tap-to-pay' },
          },
        ],
      },
    ],
  },
  {
    id: 'phone',
    label: 'Part 2 — The Phone App',
    groups: [
      {
        label: 'Bottom Navigation Bar',
        sections: [
          {
            id: 'phone-home',
            title: 'Home Screen',
            purpose: 'Your day at a glance, on the go.',
            screenshot: 'Screenshot: The phone home screen showing today’s visits and quick actions.',
            steps: [
              'Open the app.',
              'Today’s visits are at the top.',
              'Tap a visit to see the job.',
              'Use the bottom bar to move around.',
            ],
            proTip: 'Check Home before you leave the house. It already knows where you’re going first.',
          },
          {
            id: 'phone-jobs',
            title: 'Jobs Screen',
            purpose: 'The jobs assigned to you in the field.',
            screenshot: 'Screenshot: The mobile jobs list, with one job open showing notes, photos, materials and time.',
            steps: [
              'Tap **Jobs** at the bottom.',
              'Tap a job to open it.',
              'Add photos as you work.',
              'Tap a material line to edit it.',
              'Tap the bin icon to delete one.',
              'Log your time before you leave.',
            ],
            proTip: 'Photos, materials and time — do all three on site. Five minutes in the van saves an hour at the desk.',
          },
          {
            id: 'phone-inbox',
            title: 'Inbox',
            purpose: 'Team and client messages on your phone.',
            screenshot: 'Screenshot: The mobile inbox with unread conversations at the top.',
            steps: [
              'Tap **Inbox** at the bottom.',
              'Tap a conversation.',
              'Type and tap **Send**.',
            ],
            proTip: 'Messages here sync with the web app. Reply from whichever screen is closer.',
          },
          {
            id: 'phone-schedule',
            title: 'Schedule Screen',
            purpose: 'Your calendar in your pocket.',
            screenshot: 'Screenshot: The mobile schedule showing this week’s visits.',
            steps: [
              'Tap **Schedule** at the bottom.',
              'Swipe between days.',
              'Tap a visit for job details.',
            ],
            proTip: 'A new visit appearing mid-morning means the office booked you something. Glance at it after smoko.',
          },
        ],
      },
      {
        label: 'More Menu — Work',
        sections: [
          {
            id: 'phone-customers',
            title: 'Customers',
            purpose: 'Look up client details in the field.',
            screenshot: 'Screenshot: The mobile customer list with the search bar at the top.',
            steps: [
              'Tap **More**, then **Customers**.',
              'Search by name.',
              'Tap the phone number to call.',
              'Tap the address for directions.',
            ],
            proTip: 'Tapping the address opens your maps app. No more copy-pasting addresses.',
          },
          {
            id: 'phone-quotes',
            title: 'Quotes',
            purpose: 'Price up a job while standing on site.',
            screenshot: 'Screenshot: A quote being built on the phone with line items.',
            steps: [
              'Tap **More**, then **Quotes**.',
              'Tap **New Quote**.',
              'Pick the customer.',
              'Add your line items.',
              'Send it before you drive off.',
            ],
            proTip: 'A quote sent from the driveway beats one sent "tonight". Tonight rarely happens.',
          },
          {
            id: 'phone-invoices',
            title: 'Invoices',
            purpose: 'Bill the client the moment the job is done.',
            screenshot: 'Screenshot: A mobile invoice with the Tap to Pay button at the bottom.',
            steps: [
              'Tap **More**, then **Invoices**.',
              'Open the invoice — or create one from the job.',
              'Check the amount.',
              'Tap **Email invoice** — or take payment now with **Tap to Pay**.',
            ],
            proTip: 'The best time to get paid is while you’re still standing there. Use Tap to Pay.',
          },
          {
            id: 'phone-tap-to-pay',
            title: 'Tap to Pay',
            purpose: 'Take card payments right on your phone.',
            screenshot: 'Screenshot: The Tap to Pay screen showing the amount and "Hold card near the top of the phone".',
            steps: [
              'Open the invoice.',
              'Tap **Tap to Pay**.',
              'Hand your phone to the customer.',
              'They tap their card on the top edge.',
              'Wait for the green tick.',
              'Done — money goes straight to your bank.',
            ],
            proTip: 'First time? An owner or admin must finish payout setup in web Settings → Subscription first. After that it just works.',
          },
          {
            id: 'phone-tap-to-pay-help',
            title: 'Tap to Pay Help',
            purpose: 'Fix payment problems fast.',
            screenshot: 'Screenshot: The Tap to Pay error screen with a troubleshooting message.',
            steps: [
              '"Payments not set up" — finish payout setup on the web.',
              '"Couldn’t fetch connection token" — check your internet and retry.',
              'Card won’t read — hold it flat on the top edge.',
              'Still stuck? Read the full setup guide on the web app.',
            ],
            proTip: 'Nine times out of ten it’s patchy reception. Step outside or toward a window and retry.',
          },
          {
            id: 'phone-time-logs',
            title: 'Time Logs',
            purpose: 'Clock in and out of jobs.',
            screenshot: 'Screenshot: The mobile timesheet with the timer running on a job.',
            steps: [
              'Tap **More**, then **Time Logs**.',
              'Tap **Start** when you begin.',
              'Tap **Stop** when you finish.',
              'Forgot? Tap **Log Time** to add it manually.',
            ],
            proTip: 'Start the timer before you unload the van. Unloading is work time too.',
          },
          {
            id: 'phone-job-map',
            title: 'Job Map',
            purpose: 'Directions to your assigned jobs.',
            screenshot: 'Screenshot: The mobile map with today’s job pins and a directions button.',
            steps: [
              'Tap **More**, then **Job Map**.',
              'Tap a pin.',
              'Tap **Directions**.',
              'Your maps app takes over.',
            ],
            proTip: 'Trips you drive are logged for the Vehicle Logbook automatically — one less thing to remember.',
          },
          {
            id: 'phone-todo',
            title: 'To-do List',
            purpose: 'Your personal checklist on the go.',
            screenshot: 'Screenshot: The mobile to-do list with the add box at the top.',
            steps: [
              'Tap **More**, then **To-do List**.',
              'Type a task.',
              'Tick it off when done.',
            ],
            proTip: 'Add "grab fittings" the moment the customer mentions it. Standing in the supplier’s aisle is too late to remember.',
          },
          {
            id: 'phone-invitations',
            title: 'Invitations',
            purpose: 'Accept invites to join a team.',
            screenshot: 'Screenshot: The invitations screen with a pending invite and the Accept button.',
            steps: [
              'Tap **More**, then **Invitations**.',
              'Read the invite.',
              'Tap **Accept**.',
              'You now see that company’s jobs.',
            ],
            proTip: 'Nothing there? Ask the boss to invite you from web Settings → Team using this exact email address.',
          },
        ],
      },
      {
        label: 'More Menu — Account',
        sections: [
          {
            id: 'phone-profile',
            title: 'My Profile',
            purpose: 'Your name, photo and password.',
            screenshot: 'Screenshot: The profile screen with name, photo and change-password fields.',
            steps: [
              'Tap **More**, then **My Profile**.',
              'Update your name or photo.',
              'Change your password here too.',
              'Tap **Save**.',
            ],
            proTip: 'Add a real photo. Customers relax when the app shows them who’s knocking.',
          },
          {
            id: 'phone-notifications',
            title: 'Notifications',
            purpose: 'Choose which alerts your phone shows.',
            screenshot: 'Screenshot: The notification settings with toggles for jobs, messages and schedule changes.',
            steps: [
              'Tap **More**, then **Notifications**.',
              'Toggle each alert type on or off.',
              'Keep schedule changes ON.',
            ],
            proTip: 'Turn off what you don’t need, but never schedule changes — that’s how you find out a job moved.',
          },
        ],
      },
    ],
  },
]
