import type { ComponentProps } from 'react'
import {
  Bell,
  Briefcase,
  Calendar,
  Camera,
  Car,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  ClipboardList,
  Clock,
  CreditCard,
  DollarSign,
  Edit2,
  FileText,
  Folder,
  HelpCircle,
  Home,
  Inbox,
  Layers,
  Loader,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  MessageSquare,
  MoreHorizontal,
  Navigation,
  Package,
  Phone,
  Play,
  Plus,
  PlusCircle,
  RefreshCw,
  Search,
  Send,
  Settings,
  Smartphone,
  Square,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  User,
  Users,
  Wifi,
  Wrench,
  X,
  XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react-native'

const ICONS = {
  bell: Bell,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  check: Check,
  'check-circle': CheckCircle,
  'check-square': CheckSquare,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  circle: Circle,
  'clipboard-list': ClipboardList,
  clock: Clock,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  'edit-2': Edit2,
  'file-text': FileText,
  folder: Folder,
  'help-circle': HelpCircle,
  home: Home,
  inbox: Inbox,
  layers: Layers,
  loader: Loader,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  'message-square': MessageSquare,
  'more-horizontal': MoreHorizontal,
  navigation: Navigation,
  package: Package,
  phone: Phone,
  play: Play,
  plus: Plus,
  'plus-circle': PlusCircle,
  'refresh-cw': RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  smartphone: Smartphone,
  square: Square,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  'trash-2': Trash2,
  user: User,
  users: Users,
  wifi: Wifi,
  tool: Wrench,
  x: X,
  'x-circle': XCircle,
  zap: Zap,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS
type IconProps = Omit<ComponentProps<LucideIcon>, 'name'> & { name: IconName }

export function Icon({ name, ...props }: IconProps) {
  const Component = ICONS[name] ?? Circle
  return <Component {...props} />
}
